name: base
channels:
  - defaults
dependencies:
  
  
  - huggingface_hub=0.15.1
  - hvplot=0.8.4
  - imbalanced-learn=0.10.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - numpy=1.24.3
  - numpy-base=1.24.3
  - numpydoc=1.5.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - scrapy=2.8.0
  - seaborn=0.12.2
  - tqdm=4.65.0
  - transformers=4.32.1
  - twisted=22.10.0
  - pip:
      - absl-py==2.1.0
      - alpha-vantage==2.3.1
      - astunparse==1.6.3
      - bottleneck==1.3.8
      - bs4==0.0.2
      - docopt==0.6.2
      - flatbuffers==24.3.25
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - h5py==3.11.0
      - ipython==8.12.3
      - keras==3.3.3
      - libclang==18.1.1
      - mistune==3.1.1
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - nbconvert==7.16.6
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pandas==2.2.1
      - pipreqs==0.5.0
      - protobuf==4.25.3
      - rich==13.7.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - yarg==0.1.9
